# Generated by Django 4.2 on 2023-04-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=1024)),
                ('fecha', models.TextField(max_length=128)),
                ('fechaMilisegundos', models.IntegerField()),
                ('lugar', models.TextField(max_length=1024)),
                ('precio', models.IntegerField()),
                ('asientos', models.IntegerField()),
                ('asientos_vip', models.IntegerField()),
                ('asientos_cancha', models.IntegerField()),
                ('asientos_galeriaLateral', models.IntegerField()),
                ('asientos_galeriaCentral', models.IntegerField()),
                ('url', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.TextField(max_length=1)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefonico', models.IntegerField()),
                ('contrasena', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('cantidad_articulos', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.usuario'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.evento'),
        ),
    ]
