# Generated by Django 4.2 on 2023-04-25 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dv', models.TextField(max_length=1)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('numero_telefonico', models.IntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=1024)),
                ('fecha', models.TextField(max_length=128)),
                ('fechaMilisegundos', models.IntegerField()),
                ('lugar', models.TextField(max_length=1024)),
                ('imagen', models.TextField()),
                ('precio', models.IntegerField()),
                ('asientos', models.IntegerField()),
                ('asientos_vip', models.IntegerField()),
                ('asientos_cancha', models.IntegerField()),
                ('asientos_galeriaLateral', models.IntegerField()),
                ('asientos_galeriaCentral', models.IntegerField()),
                ('url', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoAsiento', models.TextField(max_length=128)),
                ('cantidad', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('cantidad_articulos', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.ticket')),
            ],
        ),
    ]
