# Generated by Django 4.2 on 2023-04-25 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_venta_ticket_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoAsiento', models.TextField(max_length=128)),
                ('cantidad', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.evento')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.ticket'),
            preserve_default=False,
        ),
    ]
