# Generated by Django 4.2 on 2023-04-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_usuario_correo_electronico_and_more'),
        ('aplicacion', '0002_evento_imagen'),
    ]

    operations = [
    ]
